//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSV_Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIEM
    {
        public int ID { get; set; }
        public string MaSV { get; set; }
        public string MaHocPhan { get; set; }
        public Nullable<double> Diem1 { get; set; }
    
        public virtual HOCPHAN HOCPHAN { get; set; }
        public virtual SINHVIEN SINHVIEN { get; set; }
    }
}
