//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSV_Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHUNGCT
    {
        public int ID { get; set; }
        public string MaHocPhan { get; set; }
        public int DVHT { get; set; }
        public string MaLop { get; set; }
    
        public virtual HOCPHAN HOCPHAN { get; set; }
        public virtual LOP LOP { get; set; }
    }
}
