//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSV_Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOP()
        {
            this.SINHVIENs = new HashSet<SINHVIEN>();
        }
    
        public string MaLop { get; set; }
        public string TenLop { get; set; }
        public int SoHocKyDaoTaoKhung { get; set; }
        public int SoHocKyDaoTaoToiDa { get; set; }
        public int HeSoQuiDoi { get; set; }
        public string MaMoHinhDaoTao { get; set; }
        public string MaDonViLienKet { get; set; }
        public string MaDonVi { get; set; }
        public int NamHoc { get; set; }
        public string MaNganh { get; set; }
        public string MaHeDaoTao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SINHVIEN> SINHVIENs { get; set; }
    }
}
