//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSV_Web
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QLSV2021Entities2 : DbContext
    {
        public QLSV2021Entities2()
            : base("name=QLSV2021Entities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BOMON> BOMONs { get; set; }
        public virtual DbSet<DIEM> DIEMs { get; set; }
        public virtual DbSet<DONVI> DONVIs { get; set; }
        public virtual DbSet<HeDaoTao> HeDaoTaos { get; set; }
        public virtual DbSet<HOCPHAN> HOCPHANs { get; set; }
        public virtual DbSet<KHOA> KHOAs { get; set; }
        public virtual DbSet<KHUNGCT> KHUNGCTs { get; set; }
        public virtual DbSet<LOP> LOPs { get; set; }
        public virtual DbSet<MoHinhDaoTao> MoHinhDaoTaos { get; set; }
        public virtual DbSet<NganhDaoTao> NganhDaoTaos { get; set; }
        public virtual DbSet<SINHVIEN> SINHVIENs { get; set; }
    
        public virtual ObjectResult<LaySVTheoLop_Result> LaySVTheoLop(string maLop)
        {
            var maLopParameter = maLop != null ?
                new ObjectParameter("MaLop", maLop) :
                new ObjectParameter("MaLop", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LaySVTheoLop_Result>("LaySVTheoLop", maLopParameter);
        }
    
        public virtual ObjectResult<LayTatCaKhoa_Result> LayTatCaKhoa()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LayTatCaKhoa_Result>("LayTatCaKhoa");
        }
    
        public virtual ObjectResult<LocLopCoSinhVien_Result> LocLopCoSinhVien()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LocLopCoSinhVien_Result>("LocLopCoSinhVien");
        }
    
        public virtual ObjectResult<LayToanBoSV_Result> LayToanBoSV()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LayToanBoSV_Result>("LayToanBoSV");
        }
    }
}
