//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSV_Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class SINHVIEN
    {
        public string MaSV { get; set; }
        public string TenSV { get; set; }
        public string GioiTinh { get; set; }
        public string NamSinh { get; set; }
        public string MaLop { get; set; }
    
        public virtual LOP LOP { get; set; }
    }
}
